// File generated by FlutterFire CLI — secrets removed.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration injected at **build time** via --dart-define.
///
/// Local development:
///   flutter run -d chrome \
///     --dart-define=FIREBASE_API_KEY=<key> \
///     --dart-define=FIREBASE_APP_ID=<appId> \
///     --dart-define=FIREBASE_SENDER_ID=<senderId>
///
/// CI / Firebase Hosting deployment: set the same variables as environment
/// secrets in your pipeline and pass them through --dart-define flags.
/// The values are baked into the compiled JS bundle at build time — they
/// never appear in source control.
class DefaultFirebaseOptions {
  // ── Build-time constants injected via --dart-define ──────────────────────
  static const String _apiKey =
      String.fromEnvironment('FIREBASE_API_KEY');
  static const String _appId =
      String.fromEnvironment('FIREBASE_APP_ID');
  static const String _messagingSenderId =
      String.fromEnvironment('FIREBASE_SENDER_ID');

  // ── Non-secret identifiers (safe to keep in source) ──────────────────────
  static const String _projectId = 'licitaciones-prod';
  static const String _authDomain = 'licitaciones-prod.firebaseapp.com';
  static const String _storageBucket = 'licitaciones-prod.firebasestorage.app';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      _assertSecretsLoaded();
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Fails fast at startup — far better than a cryptic Firebase Auth error.
  static void _assertSecretsLoaded() {
    if (_apiKey.isEmpty || _appId.isEmpty || _messagingSenderId.isEmpty) {
      throw StateError(
        '\n'
        '┌─────────────────────────────────────────────────────────────┐\n'
        '│  Firebase secrets not found.                                │\n'
        '│                                                             │\n'
        '│  Run the app with:                                          │\n'
        '│    flutter run -d chrome \\                                  │\n'
        '│      --dart-define-from-file=.env.local                    │\n'
        '│                                                             │\n'
        '│  Or set the following --dart-define flags manually:         │\n'
        '│    FIREBASE_API_KEY, FIREBASE_APP_ID, FIREBASE_SENDER_ID   │\n'
        '└─────────────────────────────────────────────────────────────┘',
      );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _apiKey,
        appId: _appId,
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        authDomain: _authDomain,
        storageBucket: _storageBucket,
      );
}
