// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return web;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // AQUÍ ESTÁ LA ÚNICA DECLARACIÓN DE 'web'
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRcljZK3ph4qtgGF5lOKnabGOVnSyNas',
    appId: '1:22058933099:web:412be49c21b52024fa8a2e',
    messagingSenderId: '22058933099',
    projectId: 'licitaciones-prod',
    authDomain: 'licitaciones-prod.firebaseapp.com',
    storageBucket: 'licitaciones-prod.firebasestorage.app',
  );
}