// File generated by FlutterFire CLI — secrets removed.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show debugPrint, defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration injected at **build time** via --dart-define.
///
/// Local development:
///   flutter run -d chrome \
///     --dart-define=FIREBASE_API_KEY=AIzaSyDjRcljZK3ph4qtgGF5lOKnabGOVnSyNas
///     --dart-define=FIREBASE_AUTH_DOMAIN=licitaciones-prod.firebaseapp.com
///     --dart-define=FIREBASE_PROJECT_ID=licitaciones-prod
///     --dart-define=FIREBASE_STORAGE_BUCKET=licitaciones-prod.firebasestorage.app
///     --dart-define=FIREBASE_APP_ID=1:22058933099:web:456d86b9b4a5d6d6fa8a2e
///     --dart-define=FIREBASE_SENDER_ID=22058933099
///
/// CI / Firebase Hosting deployment: set the same variables as environment
/// secrets in your pipeline and pass them through --dart-define flags.
/// The values are baked into the compiled JS bundle at build time — they
/// never appear in source control.
class DefaultFirebaseOptions {
  // ── Build-time constants (Hardcoded for production stability) ──────────────
  static const String _apiKey = "AIzaSyDjRcljZK3ph4qtgGF5lOKnabGOVnSyNas";
  static const String _appId = "1:22058933099:web:456d86b9b4a5d6d6fa8a2e";
  static const String _messagingSenderId = "22058933099";

  // ── Non-secret identifiers (Safe production defaults) ────────────────────
  static const String _projectId = 'licitaciones-prod';
  static const String _authDomain = 'licitaciones-prod.firebaseapp.com';
  static const String _storageBucket = 'licitaciones-prod.firebasestorage.app';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      _assertSecretsLoaded();
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Warns instead of failing at startup for easier layout development.
  static void _assertSecretsLoaded() {
    if (_apiKey == 'demo' || _appId == 'demo' || _messagingSenderId == 'demo') {
      debugPrint(
        '\n'
        '┌─────────────────────────────────────────────────────────────┐\n'
        '│  WARNING: Running with demo Firebase secrets.               │\n'
        '│  Layout will work, but Firebase features will fail.         │\n'
        '│                                                             │\n'
        '│  To use real Firebase, run with:                            │\n'
        '│    flutter run -d chrome \\                                  │\n'
        '│      --dart-define-from-file=firebase_config.json          │\n'
        '└─────────────────────────────────────────────────────────────┘',
      );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _apiKey,
        appId: _appId,
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        authDomain: _authDomain,
        storageBucket: _storageBucket,
      );
}
